import SwiftUI
import Foundation

extension Text {
    static func localized(_ key: String) -> Text {
        return Text(key)
    }
}

extension String {
    @available(*, deprecated, message: "Please use the L10n types generated by SwiftGen, for example L10n.App.save")
    var cfLocalized: String {
        return self
    }
    @available(*, deprecated, message: "Please use the L10n types generated by SwiftGen, for example L10n.Kubernetes.Cluster.edit(clusterName)")
    func cfLocalized(with arguments: CVarArg...) -> String {
        let format = NSLocalizedString(self, bundle: .main, comment: "")
        return String(format: format, arguments: arguments)
    }
}

struct L10nText: View {
    let key: LocalizedStringKey

    init(_ key: String) {
        self.key = LocalizedStringKey(key)
    }

    var body: some View {
        Text(key)
    }
} 
